name: lint-and-test
on:
  push:
    branches:
      - main
    paths:
      - "gradle/**"
      - "src/**"
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - settings.gradle.kts
      - .github/workflows/lint-and-test.yml
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "gradle/**"
      - "src/**"
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - settings.gradle.kts
      - .github/workflows/lint-and-test.yml
jobs:
  lint-and-test:
    name: lint-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Lint
        run: ./gradlew lintKotlin
      - name: Test
        run: ./gradlew test
