name: lint-and-test-main
on:
  push:
    branches:
      - main
    paths:
      - "gradle/**"
      - "**.kts"
      - gradle.properties
      - gradlew
      - gradlew.bat
      - "**.kt"
      - "**.java"
      - .github/workflows/lint-and-test-main.yml
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "gradle/**"
      - "**.kts"
      - gradle.properties
      - gradlew
      - gradlew.bat
      - "**.kt"
      - "**.java"
      - .github/workflows/lint-and-test-main.yml
jobs:
  lint-and-test-main:
    strategy:
      fail-fast: false
      matrix:
        java-version: [ '8', '11', '17' ]
    name: 'lint-and-test-main Java${{ matrix.java-version }}'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up java
        uses: actions/setup-java@v2
        with:
          java-version: '${{ matrix.java-version }}'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Lint
        run: ./gradlew lintKotlin
      - name: Test
        run: ./gradlew test
